### ISSUE TITLE
Fix broken links in README

### ISSUE THREAD

**Issue by 3for** [NilFoundation/modes#9]
[https://github.com/nilfoundaton/stream](https://github.com/nilfoundaton/stream) deprecated?

**Comment by nkaskov** [comment]
It's here now: https://github.com/NilFoundation/crypto3-stream

**Comment by 3for** [comment]
Thanks @nkaskov . Then our link in `README.md` should be changed from `https://github.com/nilfoundaton/stream` to `https://github.com/NilFoundation/crypto3-stream`

**Comment by nkaskov** [comment]
Fixed it, thanks.
